# Generated by Django 4.2.9 on 2024-03-02 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=70)),
                ("name", models.CharField(default="", max_length=30)),
                ("department", models.CharField(default="", max_length=50)),
                ("rating", models.FloatField(default=0)),
                ("num_ratings", models.IntegerField(default=0)),
                ("difficulty", models.FloatField(default=0)),
                ("would_take_again", models.CharField(default="", max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name="cachedcourses",
            name="instructor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="search.professor",
            ),
        ),
    ]
