# Generated by Django 4.2.9 on 2024-02-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoppingCart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedcourses",
            name="title",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="savedcourses",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="savedcourses",
            name="instructor",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
