# Generated by Django 4.2.9 on 2024-02-07 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "shoppingCart",
            "0002_savedcourses_title_alter_savedcourses_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="savedcourses",
            unique_together={("user", "courseID")},
        ),
    ]
