# Generated by Django 4.2.9 on 2024-02-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoppingCart", "0003_alter_savedcourses_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
