# Generated by Django 4.2.9 on 2024-02-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0004_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedcourses',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='savedcourses',
            name='sql_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='savedcourses',
            unique_together={('user', 'courseID', 'sql_id')},
        ),
        migrations.RemoveField(
            model_name='savedcourses',
            name='description',
        ),
        migrations.RemoveField(
            model_name='savedcourses',
            name='title',
        ),
    ]
