# Generated by Django 4.2.9 on 2024-03-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0005_alter_savedcourses_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcourses',
            name='notes',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
